### PR TITLE
MINOR: backend: add new parameters

### PR DESCRIPTION
**Pull request by yuzhichang**
Add external-check to global, default, and backend options.

### CODE REVIEW

**Review by mjuraga — CHANGES_REQUESTED** [review]
I wouldn't add absolute paths to README here, cause someone might have different project setups.

**Comment by yuzhichang** [comment]
@mjuraga Updated per your comments.

**Review by mjuraga — CHANGES_REQUESTED** [review]
see https://github.com/haproxytech/dataplaneapi-specification/pull/3#pullrequestreview-256374722

**Comment by yuzhichang** [comment]
@mjuraga  Updated per your comments again.

**Pull request merged**
